# Generated by Django 5.1 on 2024-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattemptsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientchartdata',
            name='medications',
        ),
        migrations.AddField(
            model_name='patientchartdata',
            name='patient_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='explanation_images/'),
        ),
    ]
