# Generated by Django 5.1 on 2024-09-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_image_questionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ImageField(upload_to='question_charts/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='quiz.question')),
            ],
        ),
    ]
