# Generated by Django 5.1 on 2024-09-16 20:43

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(upload_to=quiz.models.get_image_filename),
        ),
    ]
