# Generated by Django 5.1 on 2024-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_explanation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='default_id', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
