# Generated by Django 5.1 on 2024-09-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='quiz.question'),
        ),
    ]
