# Generated by Django 5.1 on 2024-09-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizattempt_answered_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('medications', models.TextField()),
                ('medical_history', models.TextField()),
                ('current_findings', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='quiz.question')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionChart',
        ),
    ]
