# Generated by Django 5.1 on 2024-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_detailedexplanation_question_read_more_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='explanation_image/'),
        ),
    ]
