# Generated by Django 5.1.2 on 2025-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionstatus',
            name='last_was_correct',
            field=models.BooleanField(default=False),
        ),
    ]
