# Generated by Django 5.1.2 on 2025-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquestionstatus_last_was_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='normalized_text_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('subject', 'normalized_text_key'), name='uq_subject_normtext'),
        ),
    ]
