# Generated by Django 5.1.2 on 2025-11-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_question_image_question_question_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quiz.question'),
        ),
    ]
